"""empty message

Revision ID: 4702f906188e
Revises: 51190ff4a410
Create Date: 2024-01-25 11:45:01.279272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4702f906188e'
down_revision = '51190ff4a410'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.Column('farah_discount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_collected_at'), ['collected_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_collected_at'))

    op.drop_table('price')
    # ### end Alembic commands ###
